### ISSUE TITLE
Remote Node not connecting.

### ISSUE THREAD

**Issue by Robertmor808** [EquilibriaCC/equilibria-wallet#10]
**Describe the bug**
Remote node not connecting. Unable to open wallet. Unable to restore a wallet from seed. Will not download a local node.

**To Reproduce**

**Expected behavior**
 I was expecting to be able to connect to the remote node to view my wallet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Intel Ventura
 - Browser [e.g. chrome, safari] Chrome.
 - Version [e.g. 22] 13.6.3

**Smartphone (please complete the following information):**

**Log File**
Attach Equilibrium.log
[wallet-rpc.log](https://github.com/EquilibriaCC/equilibria-wallet/files/13968072/wallet-rpc.log)

**Additional context**
19.0.0, 18.0.0, 17.2.2, 17.2.1 works but will not download a complete node or fully connect remotely, Hangs at 99.3 percent for days.

**Comment by AdminXeq** [comment]
Use only latest version as v19 and remote nodes available in here
154.38.165.93:9231
38.242.135.157:9231
213.155.160.222:9231
194.233.64.43:9231
207.244.249.105:9231
161.97.102.172:9231
62.171.181.142:9231

**Comment by Robertmor808** [comment]
Ok the ip addresses allowed to connect to the remote node but the when I try to open the wallet it just hangs there showing no progress. Also removed the wallet to test and it still won't restore from seed. Getting this error" Cannot read properties of undefined (reading 'post')

**Comment by muscleman** [comment]
blend existing remotes with new nodes
