### ISSUE TITLE
Wallet closes when "About" links are clicked

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#11]
**Describe the bug**
If the user has the wallet open, connected to a node, and fully synced, and then clicks on the menu bar on the right and then "About", and then clicks any of the links, it opens a web browser with the linked page but closes the wallet in the background on the application. If the user then closes the wallet application, the "Wallet" process hangs and does not close the wallet with the application.
-Version 19.1.0

**To Reproduce**
1. Open wallet and sync with daemon
2. Click the menu button then about
3. Click on any link
4. The wallet is now closed in the background

**Expected behavior**
When a link is clicked, the wallet does not close in the background.
When the application is closed, the wallet process also closes at the same time. 

**Desktop (please complete the following information):**
 - OS: OSX 11
 - Browser: Safari

**Additional context**
2 problems here but a main issue fix may resolve the wallet process hang.

**Comment by muscleman** [comment]
did a slight change, not sure it's fixed i don't have a mac.

code ultimately call a method in electron, could be buggy.
https://www.electronjs.org/docs/latest/api/shell#shellopenexternalurl-options

**Comment by AdminXeq** [comment]
Confirmed on windows as well

**Comment by AdminXeq** [comment]
Does not close on 19.1.3 M2 Mac

**Comment by BigslimVdub** [comment]
@AdminXeq the issue is not fixed on either mac builds, need to reopen.
Intel mac and arm (have to use intel release) v19.1.3 when clicking any link it closes the wallet to the main wallet list page and have to re-open with the password. In the background, the wallet is still open as seen in the screenshot:
Remote daemon:

<img width="990" alt="wallet still open" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/57538574-bef5-419a-b50e-729228e712da">

Same thing with local daemon:

<img width="732" alt="wallet open local" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/074be6f8-c0dc-45d4-8cb0-ca116c485d09">
