### ISSUE TITLE
TODO: Update links

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#12]
*TODO: Links need to be updated for the v19+ release on both ABOUT pages*

1. ***ADD Twitter link***
2. Discord
3. Telegram
4. ***ADD Medium link***
5. ***ADD Explorer link***

The app home page and wallet menu page both need links updated. Non-release issue but for a maintenance release.

**Comment by muscleman** [comment]
done, seems the TG landed me in channel
