### ISSUE TITLE
TODO: Update remote node list

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#13]
*The remote node list needs updating to the latest available remote nodes for end users on v19+ due to some expired nodes*

Recommended list:
154.38.165.93:9231
38.242.135.157:9231
213.155.160.222:9231
194.233.64.43:9231
207.244.249.105:9231
161.97.102.172:9231
62.171.181.142:9231

DNS could be used for specific nodes for user visibility.
This is a maintenance release.

**Comment by muscleman** [comment]
blend existing remotes with the new nodes
