### ISSUE TITLE
Wallet will not open

### ISSUE THREAD

**Issue by Robertmor808** [EquilibriaCC/equilibria-wallet#14]
Wallet will not open.  It just hangs there showing no progress. Also removed the wallet to test and it still won't restore from seed. Getting this error" Cannot read properties of undefined (reading 'post') Latest version 19.1.1. Tested on both Windows and Mac Intel

**To Reproduce**
Click on load wallet.

**Expected behavior**
To open wallet and show progress connecting to node.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac 13.6.3 and Windows 11
 - Browser chrome, safari, edge

**Comment by AdminXeq** [comment]
Do you have remote node scan enabled in settings ?
I cannot reproduce, I can create new wallet using remote eu.equilibriacc.com node as well as import from seed words

**Comment by AdminXeq** [comment]
![remote](https://github.com/EquilibriaCC/equilibria-wallet/assets/114882533/5c8f9998-0652-41d2-9baa-ae8f9e1b8bc4)

**Comment by Robertmor808** [comment]
Tested 19.1.2 and working as expected.
