### ISSUE TITLE
Unable to restore from seed with remote daemon mac intel

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#15]
**Describe the bug**
Unable to restore from seed while using remote node on mac intel. Mac arm works as expected.

**To Reproduce**
1. Open app and click restore from seed
2. Enter wallet name, passphrase, restore height or date, and password
3. Click restore account
4. User is prompted with RED error "Cannot read properties of undefined (reading 'post')

**Expected behavior**
User can restore wallet using remote node

**Screenshots**
<img width="1079" alt="cannot restore from seed" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/0b4ed63e-50f1-48ab-8ca0-b77a84f0efb8">

**Desktop (please complete the following information):**
 - OS: 11.7.10 intel
 - Version 19.1.1

**Additional context**
Remote Daemon not using ```--restricted-rpc```

**Comment by AdminXeq** [comment]
![remote](https://github.com/EquilibriaCC/equilibria-wallet/assets/114882533/75522a67-4106-44cc-a3fc-5a983e06343c)
Check this enable remote scan
