### ISSUE TITLE
Import wallet string error in file name box

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#16]
**Describe the bug**
When attempting to import a wallet from a file, the text box has a string error not text.
When a file is selected, the file path is correct with no errors. 

**To Reproduce**
1. Open application
2. Select "Import account from file"
3. See file name text box with string error

**Expected behavior**
The text box shows the appropriate text

**Screenshots**
<img width="1093" alt="import wallet string error" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/819a54af-0fe3-43d0-acfd-798a2f09859a">

**Desktop (please complete the following information):**
 - Version:  OSX Intel 19.1.1 release

**Comment by AdminXeq** [comment]
Confirmed on windows as well
