### ISSUE TITLE
Unable to import account from file MAC

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#17]
**Describe the bug**
When attempting to import an account from file, the application errors out with Error "Failed to copy wallet" and the wallet is not imported as expected. Happens on MAC M1 and Intel. 

**To Reproduce**
1. Open application
2. Select "Import account from file"
3. Enter the new account name, select the account file, and a password
4. Select "Import Account"
5. RED error prompt with text "Failed to copy wallet"

**Expected behavior**
Wallet is imported as expected

**Screenshots**
![import fail](https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/6706d179-83e5-4de9-b1c4-efa51fbabfbc)

**Desktop (please complete the following information):**
 - OS: OSX 11.7.10
 - Version: 19.1.1

**Additional context**
For fun, all 3 wallet related files throw this error. The address.txt should throw an unsupported file error and or error saying select .keys file :)

**Comment by AdminXeq** [comment]
Confirmed on windows as well

**Comment by muscleman** [comment]
Fixed with commit e5f690d0e53cbeb0bc3c8e7a82e22b013029e077
