### ISSUE TITLE
Switching from remote node to local daemon while wallet open does not restart app MAC arm

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#18]
**Describe the bug**
When user opens the wallet with settings set to remote node only and then goes to settings to change daemon type to local only, the app prompts the restart app popup however when exit is clicked the app closes and does not restart with local daemon mode. 

**To Reproduce**
1. Open app and wallet with remote node set in daemon config and start sync. 
2. GO to main settings and daemon settings and change to local daemon and continue.
3. Hit the exit button and app closes and does not change to local daemon.

**Expected behavior**
App restarts with local daemon mode.

**Desktop (please complete the following information):**
 - OS: OSX 11.7.10 MAC M1
 - Version: 19.1.1

**Additional context**
Activity monitor shows wallet process stuck open after this. Force close wallet process and open app and local daemon works as expected.

**Comment by muscleman** [comment]
believe the expected behavior when exiting the application after a config change is to retain the unchanged settings.

clicking the save button provides the expected behavior.
