### ISSUE TITLE
New wallet loses all settings, database, blockchain and wallet settings

### ISSUE THREAD

**Issue by gab81** [EquilibriaCC/equilibria-wallet#2]
I have just downloaded and installed the 17.1 wallet onto windows.

You lose the database and your own wallet settings if you run the installer as normal and install over, which most people would do for an upgrade - download exe launch it and that's it. Simple setup, external drive X:\EquilibriaCC Wallet

Why does it delete everything? 

⚠️🚨 Why we cannot get simple things right? I know there's a lot of effort in the project BUT. 

I had the database folder with the whole blockchain, like 9GB and now guess what, after the install is GONE so i need to re-sync.

This happened in the previous release and in the previous one as well.

So i have to say it again: can you guys fix it when there are these "hardforks"? 

Good i have my seed saved but if i didnt i would have lost it all.

All other wallets don't have these issues, i have Pirate, Monero, etc all don't lose everything every time there's a hard fork.

thank you

**Comment by muscleman** [comment]
fuck off

**Comment by AdminXeq** [comment]
Provide issue with template available on this github repository.
I can't reproduce your bug, update went smooth without data lost or wallets.
Default patch for program install is on :
C:\Users\%USERNAME%\AppData\Local\Programs\EquilibriaCC Wallet\
C:\ProgramData\equilibria for database
and for wallet as example 
C:\Users\%USERNAME%\Documents\equilibria
Here is config.json where you can also adjust your settings
C:\ProgramData\equilibria\gui
