### ISSUE TITLE
String text error for sub address in transfers tab

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#21]
**Describe the bug**
The string text is missing in the sub address tab and showing string message not the physical text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open wallet app and select transfers tab
2. Select a sub address
3. The first line string at the top is showing actual string not the text

**Expected behaviour**
Text should be shown

**Screenshots**
![IMG_0435](https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/ddc68752-73a1-4f4e-b166-ad4362beef02)

**Desktop (please complete the following information):**
 - OS: macOS M1
 - Version: 19.2.1

**Additional context**
Nein

**Comment by muscleman** [comment]
19.1.3 has this fixed. commit 715e30de2d1a462ec892141767d585307b58f78b
