### ISSUE TITLE
Feature Request: Add oracle node filter “My Nodes” option

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#23]
**Describe the feature request**
Currently there is no option to filter to display only your own nodes. As XEQ grows in popularity the list of open or closed nodes may swell to a very high number creating it a task to find your nodes status. If a user operates a high number of nodes it will be useful to have this option in the gui. See screenshot for example option area to allow filtering of my nodes.

**Screenshots**
![IMG_0438](https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/042cbdca-d60b-4aa6-92eb-10933f65205f)

**Comment by AdminXeq** [comment]
you see them on left side as operator or contributor on top of list using ALL from drop down list
<img width="115" alt="Zrzut ekranu 2024-01-29 o 00 14 48" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/114882533/01eb9731-8f8f-4758-8a9f-f6138d7b26a1">

**Comment by AdminXeq** [comment]
added in 19.1.4
