### ISSUE TITLE
Wallet process hangs when gui application is closed

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#24]
**Describe the bug**
When closing the wallet and application, the wallet process hangs open syncing in the background until it is quit manually or the pc is rebooted. This could allow a potential attack vector to users wallet from malicious actors who have access to the pc.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app and login to wallet
2. Close wallet
3. Close application
4. Check background process and see that the “wallet” process is still running

**Expected behavior**
When closing the application and or wallet, the rpc process is stopped and wallet is fully closed.

**Screenshots**
![IMG_0437](https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/edbd37a6-0a12-46d6-9ffc-206bc3efd97a)

**Desktop (please complete the following information):**
 - OS: MacOS intel or arm, windows 10

**Additional context**
double force quit upon exit not single quit

**Comment by muscleman** [comment]
wallet connection is over https and the user/password are auto generated each time you open the wallet. both user/pass are 64 bytes long. So security ain't an issue.

i would like to know a copy extra things.
1. is this only occurring during a local sync?
2. we don't have an arm release, however OS above states all three. is this just a mac thing?

**Comment by BigslimVdub** [comment]
1. is this only occurring during a local sync? - Happens on local or remote daemon use
2. we don't have an arm release, however OS above states all three. is this just a mac thing? - Happens on all 3 OS

**Comment by BigslimVdub** [comment]
issue resolved on 19.1.4, checked on Mac intel and M1 and wallet process stops after closing application.
