### ISSUE TITLE
Failed to open wallet

### ISSUE THREAD

**Issue by krlm080** [EquilibriaCC/equilibria-wallet#26]
**Describe the bug**
After the wallet is loaded, and after entering the password, I get the error message:"Failed to open wallet".

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
I expected the wallet to open.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Brave
 - Version: 11

**Smartphone (please complete the following information):**

**Log File**
Attach Equilibrium.log

**Additional context**
Haven't open the wallet for over a year?

**Comment by AdminXeq** [comment]
Import wallet from seed words using latest version and wait for full sync

**Comment by BigslimVdub** [comment]
Did you update to the latest new wallet 19.1.3? You may also need to use an updated remote node if you are not running local daemon.

**Comment by krlm080** [comment]
Thanks for the follow-up. I was able to open the wallet in the end only founding out...there was nothing on it ;)
