### ISSUE TITLE
Copy address from home page shows string not string text

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#27]
**Describe the bug**
From the main page after opening the application if a user right-clicks an address and selects the copy address, the notification shows the string, not the string message. See photo for reference. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app
2. Right-click an address
3. Select "Copy Address"
4. String error shows in message popup

**Expected behaviour**
String text is shown

**Screenshots**
<img width="916" alt="copy address string" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/cb313cd7-b944-412f-b507-81d6c32fd4ac">

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 19.1.3

**Comment by muscleman** [comment]
yep, dropped the extra `e` and all works

**Comment by BigslimVdub** [comment]
messageeeeees

**Comment by AdminXeq** [comment]
Fixed in 19.1.4
