### ISSUE TITLE
Create TX window string error send-to name

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#28]
**Describe the bug**
String error for TX address name text

**To Reproduce**
Steps to reproduce the behaviour:

**Go to '...'
1. Sync wallet and create a Transfer
2. In the transfer window and click the save address box 
3. The send-to wallet name is the string not text

Expected behaviour**
Text is shown not string

**Screenshots**
<img width="254" alt="send to name string" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/dc21c56e-a789-422d-b272-26addccb29b2">

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 19.1.3

**Comment by AdminXeq** [comment]
Fixed in 19.1.4
