### ISSUE TITLE
Generate QR code "OK" button text is white on white background

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#29]
**Describe the bug**
When generating a QR code, the ok button text is missing or the same color white as the button itself. 

**To Reproduce**
1. Generate a QR code by either the receive window address or other from main page
2. See the lower button issue of white on white or missing text

**Expected behavior**
The button has text that is BLACK

**Screenshots**
<img width="319" alt="QR code button" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/1af2ba7e-2d54-4f18-919d-07a4bdd26f96">

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 19.1.3

**Additional context**
User can click off to the side to get QR code window to close.

**Comment by AdminXeq** [comment]
Fixed in 19.1.4
