### ISSUE TITLE
Unable to stake XEQ using 17.2.1 AppImage Linux GUI application on Linux Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by TheLawofNature** [EquilibriaCC/equilibria-wallet#3]
---
name: Bug report
about: Create a report to help us improve
title: 'Unable to stake XEQ using 17.2.1 AppImage Linux GUI application on Linux Ubuntu 22.04 LTS'
labels: ''
assignees: ''

---

**Describe the bug**
Using the AppImage version of GUI wallet 17.2.1 on Ubuntu 22.04.2 LTS, running a local daemon, when attempting to stake XEQ to open nodes, the application allows me to enter the amount to stake, then it allows me to enter my password, but after entering my password, I invariably receive a red message box at the bottom that says, "Transaction would be too large. Use the sweep all function in your wallet.  After 10 confirmations, try staking again."  I have completed the sweep all function and allowed it to confirm, but I am still receiving the same error.  I have confirmed my unspent outputs are down to 1 on my Receive tab but I still receive the message telling me to sweep all when trying to stake.

**To Reproduce**
1. Go to the Staking Pools tab
2. Click the "STAKE" button on an open node
3. Enter a valid amount to stake and click the "CONFIRM STAKE" button
4. Enter wallet password and click the "STAKE" button
5. See error message at bottom (red pop-up that says, "Transaction would be too large. Use the sweep all function in your wallet.  After 10 confirmations, try staking again.")  This error fires even after I have performed the sweep all function and waited for the transaction to be confirmed.

**Expected behavior**
I expect another window to pop up displaying the fee for staking, and asking me to confirm again.  I then expect a confirmation message indicating that the stake request was successful.  I was able to stake this way using prior versions of the wallet but never with version 17.2.1.

**Screenshots**
![Screenshot from 2023-05-13 09-13-48](https://github.com/EquilibriaCC/equilibria-wallet/assets/133511644/11ec3b7f-4ec7-4b7f-ab0b-008bbc425487)

![Screenshot from 2023-05-13 09-10-30](https://github.com/EquilibriaCC/equilibria-wallet/assets/133511644/66f0bab3-53e6-48f9-bf9c-4fc2a2b84aa7)

![Screenshot from 2023-05-13 09-08-34](https://github.com/EquilibriaCC/equilibria-wallet/assets/133511644/acb8232d-571c-41df-8218-70e44d0f83dd)

![Screenshot from 2023-05-13 09-08-45](https://github.com/EquilibriaCC/equilibria-wallet/assets/133511644/0ba26040-8284-4a84-841c-9a11d6afeb08)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser N/A

**Smartphone (please complete the following information):**

**Log File**
[Equilibria.log](https://github.com/EquilibriaCC/equilibria-wallet/files/11469818/Equilibria.log)

**Additional context**
While buggy, I was always able to stake portions of my balance using prior versions of the GUI wallet (versions 16.0 and lower).  This issue of not being able to stake any portion of my balance has only started on version 17.2.1.  I just tested staking with version 17.1 and though I received an error message for one of the transactions, the staking transactions were successful.

**Comment by AdminXeq** [comment]
use sweep_all function from options
