### ISSUE TITLE
Contributing to staking node TX confirm fee cancel showing string not "cancel"

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#30]
**Describe the bug**
When contributing to a staking node and confirming your amount, the TX fee window shows the "cancel" button as the string not the text "cancel". This same popup for standard TX doesn't show this string error. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a node to stake to
2. Enter your contribution amount
3. Select ok
4. Enter your password and hit ok
5. Wait for TX fee popup to show and see error

**Expected behaviour**
TX fee window shows Cancel text not string

**Screenshots**
<img width="403" alt="Screen Shot 2024-02-26 at 7 39 26 PM" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/f9e8aa6a-a5a0-4997-9295-0db0d0dc9784">

**Desktop (please complete the following information):**
 - OS: OSX
 - v19.1.4 release

**Comment by AdminXeq** [comment]
fixed in 19.1.5
