### ISSUE TITLE
Pending TX is marked "Failed" until it has one confirmation

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#31]
**Describe the bug**
When a user sends a transaction, the GUI wallet marks this transaction as "Failed" in the transactions tab instead of pending when block times are longer than 2 minutes.

**To Reproduce**
1. Send a TX
2. Wait for TX to process and show in "Transactions" tab
3. See the TX is marked as FAILED in red

**Expected behavior**
TX is marked as Pending not Failed because it did not fail

**Desktop (please complete the following information):**
 - OS: OSX 14.6.1

**Additional context**
This is an existing issue since at least v19

**Comment by muscleman** [comment]
Believe this is not an electron issue. here is the electron code, it just concats all the arrays from the get_transfers request to wallet.

const data = await this.sendRPC("get_transfers", options)

      if (data && data.result) {
        const types = [
          "in",
          "out",
          "pending",
          "failed",
          "pool",
          "miner",
          "snode",
          "gov",
          "stake"
        ]
        types.forEach((type) => {
          if (data.result.hasOwnProperty(type)) {
            wallet.transactions.tx_list =
                            wallet.transactions.tx_list.concat(
                              data.result[type]
                            )
          }
        })
