### ISSUE TITLE
Wallet Issue: Update from v12.0.0 to v17.2.2

### ISSUE THREAD

**Issue by cryptotrinity** [EquilibriaCC/equilibria-wallet#6]
- Using an older MacBook Pro; intel core i5 (MacOS 12.7.2 Monterey)
-Had a pending transaction from over a year ago that I had never been able to see until now
-I can see full balance in desktop wallet v12.0.0
-Unable to send asset from wallet to exchange
-Error shows "Daemon is busy" when I hit "SEND" button

-Downloaded new v17.2.2
-Click program icon to open and window opens with warning "Warning: daemon not found, using remote node"
-Entered password but wallet will not open
-It just spins and spins

<img width="950" alt="Screen Shot 2023-12-24 at 8 42 29 AM" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/154745007/0d72fea4-73dd-4bb4-bd2b-ca275225625e">

Any help one can provide is appreciated.

**Comment by AdminXeq** [comment]
Export your seed words on old version, install new wallet from latest release , wait for full sync, import wallet from seed words.
Between those version was few major changes related to daemon, wallet cli, gui and whole network, but still your coins are safe as soon as you got mnemonic words to recover wallet in latest version

**Comment by cryptotrinity** [comment]
It didn’t seem I could load the new wallet version due to my current mac hardware. I’m using a MacBook Pro; intel core i5 (MacOS 12.7.2 Monterey).

Will v17.2.2 load on this machine? Or was it because I tried to load existing wallet with existing password?

Thanks for reaching out. I 1,000% appreciate it.

**Comment by AdminXeq** [comment]
Just import under new name with latest GUI and you should be fine, old wallet file may not work on current release.
There will be macOS ( intel) and maOS(arm m1/m2) version
