### ISSUE TITLE
Mac ARM zip wallet missing welcome string text v18.0.0

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#7]
**Describe the bug**
v18.0.0 mac arm zip wallet has missing string message on creation of new wallet:
https://github.com/EquilibriaCC/equilibria-wallet/releases/download/v18.0.0/EquilibriaCC-Wallet.18.0.0.mac.arm64.zip

**To Reproduce**
download the zip and open the wallet executable when no config file present on pc

**Expected behavior**
String message shows proper text

**Screenshots**
<img width="825" alt="XEQ 18 0 mac arm zip error" src="https://github.com/EquilibriaCC/equilibria-wallet/assets/30030687/0cbe356f-3ac4-41af-9bdb-53f66691af99">

**Desktop (please complete the following information):**
 - OS: MacOS 11.7.10
 - M1

**Comment by muscleman** [comment]
incorrect syntax for I18n interpolation in a html element
