### ISSUE TITLE
v18.0.0 unable to connect to remote node with restricted rpc set

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/equilibria-wallet#8]
**Describe the bug**
With version 18.0.0 wallet, user is unable to connect to a remote node when --restricted-rpc is set on the daemon, the wallet jsut loads and loads and loads but will not open. This causes wallet-rpc process to hang up when attempting to exit the application. Only force quitting the wallet-rpc process allows wallet app to close. M1 zip binaries. If remote node does not have restricted rpc set, it will connect the first try.
https://github.com/EquilibriaCC/equilibria-wallet/releases/download/v18.0.0/EquilibriaCC-Wallet.18.0.0.mac.arm64.zip

**Expected behavior**
Wallet should be able to connect to remote node with restricted rpc set. Also when closing the app, there should be no hangup of wallet-rpc.

**Comment by AdminXeq** [comment]
Public nodes 
154.38.165.93:9231
38.242.135.157:9231
213.155.160.222:9231
194.233.64.43:9231
207.244.249.105:9231
161.97.102.172:9231
62.171.181.142:9231
